### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jschultz** [shazow/sqlalchemygrate#7]
Hello all,

Sorry for the newbie question but I'm having trouble getting sqlalchemy off the ground. All I want to do is replicate databases using different database engines, with the occasional small change to the data structures.  Could someone help me a little, perhaps by explaining:
1. What is model.meta:metadata mean? Does it mean a Python module called 'model'?
2. In what format is the metadata represented? Can I do a reflection do generate a metadata description?
3. Is there anything else I need to know or source of information?

Many thanks,
Jonathan

**Comment by shazow** [comment]
If you're a beginner with SQLAlchemy, this might not be the best package for you. It's fairly manual, advanced, and contrived. I'll try to answer your questions but unfortunately I can't promise a great experience for beginners with this package, especially since I'm not actively using it myself right now.

1. What is model.meta:metadata mean? Does it mean a Python module called 'model'?
    That's a common notation for importing a specific object via a string input. It means "object metadata inside of module model.meta". That is, you could have an instance named `metadata` inside of `.../model/meta.py`. The `metadata` target is referring to an instance of [SQLAlchemy's MetaData](http://docs.sqlalchemy.org/en/latest/core/metadata.html#sqlalchemy.schema.MetaData) type which contains the binding of the schema.

2. In what format is the metadata represented? Can I do a reflection do generate a metadata description?
    See the above link. Basically, setup your model normally to use SQLAlchemy, make sure everything is working, _then_ try to hook up sqlalchemygrate.

Specifically for migrations, I would recommend using Alembic: http://alembic.zzzcomputing.com/

It's built by the author of SQLAlchemy and is actively maintained, so it's much better integrated and documented.

I'm going to close this issue for now just so that I don't need to keep track of it, but feel free to respond with more questions. :)

**Comment by jschultz** [comment]
Thanks for your patience, that is most helpful. For the benefit of anyone else who might also be lost, I found that sqlacodegen was perfect for generating a usable metadata file. So, for example, if you reflect on an existing database with something like:
> sqlacodegen \<dbengine\> --outfile \<dbname\>.py

then the resulting file \<dbname\>.py can be used by sqlalchemygrate as follows:

> grate migrate \<dbname\>:metadata \<fromdbengine\> \<todbengine\>

**Comment by shazow** [comment]
That is handy, thanks for sharing!
